---
development: &default
    entorno: DESARROLLO ***
    serverPort: 3001
    views:
        engine: .jade
        extension: .jade
    email:
        service: gmail
        user: vic.vcp1@gmail.com
        pass: 06037650580
        from: vic.vcp1@gmail.com

    html:
        minify: true
        css:
            compress: true
            stylusPrecompile: true
    controllers:
        default: home
    languages:
        default: en
        list: [en, es, fr, pt, jp]
    
    session:
        cookieDomain: 51.15.136.155
        maxAge: 3600000
        cookiePrefix: 'svSession_'
        path: '/'
        httpOnly: true,
        secret: 933593b7aedb2c018fab87fb5ada6a2c
    
    upload:
        root: uploads/files



production: 
    entorno: PRODUCCION ***
    serverPort: 3001
    views:
        engine: .jade
        extension: .jade
    email:
        service: gmail
        user: vic.vcp1@gmail.com
        pass: 06037650580
        from: vic.vcp1@gmail.com   
    html:
        minify: true
        css:
            compress: true
            stylusPrecompile: true
    controllers:
        default: home
    languages:
        default: en
        list: [en, es, fr, pt, jp]
    
    session:
        cookieDomain: 51.15.136.155
        maxAge: 3600000
        cookiePrefix: 'svSession_'
        path: '/'
        httpOnly: true,
        secret: 933593b7aedb2c018fab87fb5ada6a2c
    
    upload:
        root: uploads/files
